apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: csharp-api
  description: csharp-api details
spec:
  type: openapi
  lifecycle: production
  owner: guest
  system: csharp-api-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: csharp API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...
